### ISSUE TITLE
Another approach (not an issue)

### ISSUE THREAD

**Issue by steipete** [jivadevoe/UIAlertView-Blocks#1]
I am using uialertview with blocks in serveral apps; having a slightly different, less verbose approach - you also might find interesting.

https://github.com/steipete/PSFoundation/blob/master/Utils/PSAlertView.h

Example Code:

```
  PSAlertView *alert = [PSAlertView alertWithTitle:alertTitle message:alertMessage];
  [alert setCancelButtonWithTitle:LocalizedString(@"Okay") block:^{}];
  [alert addButtonWithTitle:LocalizedString(@"Retry") block: ^{
    NSError *error = nil;
    [self sendMessage:message error:&error];
  }];
  [alert show];
```

**Comment by jivadevoe** [comment]
Cool, I like your approach, I might add a similar "addButtonWithTitle" method to this code.  I'm not hugely happy with the "make all your event handlers and then create the alert box" because it's not the way I think... but it matches with the traditional API so that's the way I went.
