### ISSUE TITLE
ARC Parse Issue

### ISSUE THREAD

**Issue by MaximKeegan** [jivadevoe/UIAlertView-Blocks#18]
A lot of "UIAlertView+Blocks.m:43:41: '__bridge' casts have no effect when not using ARC" warnings when using in non ARC project

**Comment by jivadevoe** [comment]
If you're using this in a non-ARC project, you're 'doing it wrong.'

This code requires ARC now.

If you browse back through the history, you can get the version that didn't support ARC and use that instead if you'd like.
