### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by RyanCopley** [jivadevoe/UIAlertView-Blocks#36]
Could you add this to Cocoapods?

Thanks,
Ryan

**Comment by jivadevoe** [comment]
No, but you can. :)

In all seriousness... I don't use CocoaPods, so I don't know what needs to happen for that.  Some other users have submitted something they said was needed for it to work with CocoaPods and I merged it.  I don't know what else needs to happen for that.

**Comment by RyanCopley** [comment]
I can do it no problem if you could do one thing for me. I will create the podspec and send a pull request, but I will need you to create a tag (v1.1 or so, let me know beforehand) of the latest version (v1.0 will be 9 commits behind master).

If you are cool with that, I can do the rest

**Comment by jivadevoe** [comment]
I think we already did all that didn't we?  There's a 1.0 release and a podspec already in the repo.

**Comment by RyanCopley** [comment]
I must have been multitasking at work... you're right, haha. You can disregard this issue. Also, you should look into trying cocoa pods... they make life easier if you do a lot of iOS dev :)

**Comment by jivadevoe** [comment]
Hah, ok, no worries. :)

**Comment by bjornartollaksen** [comment]
I just sent a pull request to the CocoaPods/Specs repo: https://github.com/CocoaPods/Specs/pull/8006

@jivadevoe: Feel free to chime in if any issue arises.
