### ISSUE TITLE
pod install: Unable to read the license file

### ISSUE THREAD

**Issue by vvit** [jivadevoe/UIAlertView-Blocks#37]
Hi, thanks for the great extension.
When I try to install new pods with 'pod install' I get this:

```
[!] Unable to read the license file `[project_dir]/Pods/UIAlertView-Blocks/LICENSE` for the spec `UIAlertView-Blocks (1.0)`
```

Nothing critical but can it be fixed?
Thanks a lot.

**Comment by bjornartollaksen** [comment]
I believe this is because the 1.0 tag points to a commit that does not have the LICENSE file in it (the LICENSE file was added in ).

@jivadevoe: You can fix this by deleting the tag and recreating it with the following commands (assuming you are up-to-date locally):

```
git tag -d 1.0
git push origin :refs/tags/1.0
git tag -a 1.0 -m "Version 1.0"
git push --tags
```

**Comment by chrismaddern** [comment]
Or just make a new tag 1.0.1.

Any chance you can do this @jivadevoe? It's our only Cocoapods warning :( haha

**Comment by Miserlou** [comment]
+1, fix the pod please!

We get the same error, makes our pod's install process look kind of shoddy! :)

**Comment by jivadevoe** [comment]
Did what @bjornartollaksen suggested.

Does it work now?

**Comment by WearFlatShoesToWalkTheWorld** [comment]
很烦,我也遇到了这个问题!!    [!] Unable to read the license file `[project_dir]/Pods/BmobSDK/LICENSE` for the spec `BmobSDK (2.1.5)`

**Comment by housenkui** [comment]
i follow  @bjornartollaksen  ,it's do work. We can draft a new Release .example   1.0.1

**Comment by fjingquan** [comment]
i get the same error, Unable to read the license file `/Users/zhaocaihong/Desktop/Education_Teacher /EducationTch/Pods/UMessage/LICENSE` for the spec `UMessage (1.4.0)`
